### ISSUE TITLE
How to install/use your library

### ISSUE THREAD

**Issue by basementmedia2** [josephpal/esp32-Encrypt#8]
Hi,

i am an arduino beginner, so please be patient ;-)

I have downloaded your library and copied the folder to the arduino library path.
But when i start arduino IDE your library is not shown (in the examples folder) ;-(
What am i doing wrong?

Best wishes
Daniel

**Comment by basementmedia2** [comment]
OK, got it. Had to add the library.properties file.
Thank you for this great little library!

**Comment by josephpal** [comment]
> OK, got it. Had to add the library.properties file. Thank you for this great little library!

I am glad that you figured it out...actually it is not a real library, more a class which you can include. It only has to be in the same directory with your ino project file...
